version: '3.0'
services:
  registrationdb:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=mySqlPass**123

    networks:
      backend:
        ipv4_address: 172.18.0.2

  redis:
    image: redis:latest
    ports:
        - "6379:6379"
    networks:
      backend:
        ipv4_address: 172.18.0.3

  smtpapi:
    image: tdmai/smtpapi
    ports:
        - "5001:5001"
    networks:
      backend:
        ipv4_address: 172.18.0.4

  registrationapi:
    image: registrationapi
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=8wt#&^6u+xZA(LOfBwJL
      - CONFIG_FILE=./config.json

    networks:
      backend:
        ipv4_address: 172.18.0.5

networks:
  backend:
    ipam:
      config:
        - subnet: 172.18.0.0/24