version: '3.0'
services:
  registrationdb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=mySqlPass**123
    container_name: registrationdb
    networks:
      backend:
        ipv4_address: 172.18.0.2

  redis:
    image: redis:latest
    ports:
        - "6379:6379"

    container_name: redisdb
    networks:
      backend:
        ipv4_address: 172.18.0.3

  smtpapi:
    image: tdmai/smtpapi:latest
    ports:
        - "5001:5001"

    container_name: smtpapi

    networks:
      backend:
        ipv4_address: 172.18.0.4

  registrationapi:
    image: tdmai/registrationapi:latest
    ports:
      - "5000:5000"

    container_name: registrationapi

    environment:
      - FLASK_ENV=production
      - SECRET_KEY=8wt#&^6u+xZA(LOfBwJL
      - CONFIG_FILE=/usr/src/config/config.json
    volumes:
      - ./config:/usr/src/config
    networks:
      backend:
        ipv4_address: 172.18.0.5

networks:
  backend:
    ipam:
      config:
        - subnet: 172.18.0.0/24
