version: '1.0'
services:
  mysql:
    image: mysql:latest
    ports:
      - 8083:3306
    volumes:
      - ./registrationdb:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: mySqlPass**123
      MYSQL_DATABASE: registrationdb